version: '3.5'
services:
  apm:
    image: docker.elastic.co/apm/apm-server:6.4.0
    restart: always
    ports:
      - "8200:8200"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - "discovery.type=single-node"
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/volume/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    restart: always
    ports:
      - "5601:5601"
  