apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:master
          args:
            - "-config.file=/etc/promtail/promtail_config.yaml"
          resources: {}
          volumeMounts:
            - mountPath: /etc/promtail
              name: promtail-conf
            - mountPath: /var/log
              name: promtail-log
      restartPolicy: Always
      volumes:
        - name: promtail-conf
          configMap: 
            name: promtail
            items: 
              - key: promtail
                path: promtail_config.yaml
        - name: promtail-log
          hostPath:
            path: /var/k8s/volumes/default/promtail
