apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  GF_SERVER_ROOT_URL: "http://grafana.nuc.io"
  GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource,grafana-kubernetes-app,grafana-worldmap-panel
