apiVersion: v1
kind: Service
metadata:
  name: apm
  labels:
    app: apm
spec:
  ports:
  - name: apm
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: apm
  sessionAffinity: None
  type: NodePort
