apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: apm
spec:
  rules:
    - host: apm.nuc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apm
                port:
                  number: 8200
            
