apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  mysql-custom-cnf: |
    [client]
    default-character-set=utf8mb4
    [mysqld]
    innodb_buffer_pool_size=800M
    max_connections=500
