apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  mysql-custom.cnf: |
    [client]
    default-character-set=utf8mb4
    [mysqld]
    innodb_buffer_pool_size=800M
    max_connections=500
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    read-only
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:8
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo [mysqld] > /etc/mysql/conf.d/server-id.cnf
              echo server-id=$((1 + $ordinal)) >> /etc/mysql/conf.d/server-id.cnf
              cp /mnt/config/mysql-custom.cnf /etc/mysql/conf.d
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/config/master.cnf /etc/mysql/conf.d
              else
                cp /mnt/config/slave.cnf /etc/mysql/conf.d
              fi
          volumeMounts:
            - name: mysql-config
              mountPath: /mnt/config
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
        - name: sync-data
          image: mysql:8
          command:
            - bash
            - "-c"
            - |
              set -ex
              echo TODO
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8
          envFrom:
            - secretRef:
                name: mysql
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql

      restartPolicy: Always
      volumes:
        - name: conf
          emptyDir: {}
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None
