apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
data:
  minio_access_key: "MzRGVFpLMjFQUkFaREdaSUVVOEE="
  minio_secret_key: "bUM2anVIL083NnBraXIzdjQvS2hNZUNkTDRURzlzV0E0L2NPZ1hnKw=="
