apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /export
          env:
            - name: MINIO_ACCESS_KEY
              value: 34FTZK21PRAZDGZIEU8A
            - name: MINIO_SECRET_KEY
              value: mC6juH/O76pkir3v4/KhMeCdL4TG9sWA4/cOgXg+
          resources: {}
          volumeMounts:
            - mountPath: /export
              name: minio
      restartPolicy: Always
      volumes:
        - name: minio
          hostPath:
            path: /btrfs/data/volumes/default/minio
