apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:3
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra
      restartPolicy: Always
      volumes:
        - name: cassandra
          hostPath:
            path: /var/k8s/volumes/default/cassandra
