apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "9042"
      port: 9042
      targetPort: 9042
