apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.5
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: zookeeper-data
            - mountPath: /datalog
              name: zookeeper-datalog
      restartPolicy: Always
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /var/k8s/volumes/default/kafka/zookeeper-data
        - name: zookeeper-datalog
          hostPath:
            path: /var/k8s/volumes/default/kafka/zookeeper-datalog
